### ISSUE TITLE
Error 403 when getting widevine license

### ISSUE THREAD

**Issue by GladistonXD** [glomatico/spotify-web-downloader#70]
```
Traceback (most recent call last):
  File "spotify_web_downloader/utils.py", line 8, in check_response
    response.raise_for_status()
  File "requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spotify_web_downloader/cli.py", line 466, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spotify_web_downloader/downloader_song.py", line 71, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spotify_web_downloader/spotify_api.py", line 111, in get_widevine_license_music      
    check_response(response)
  File "spotify_web_downloader/utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "spotify_web_downloader/utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 403:
```

**Comment by blackicedbear** [comment]
Had the same issue, seems the hard coded WVD got blocked by Spotify. Fixed it by using one from Android Emulator from Android Studio.

**Comment by GladistonXD** [comment]
I was thinking of using the WVD key directly via web drive

**Comment by GladistonXD** [comment]
> Usei este guia aqui: https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair-from-AVD

I will test

**Comment by glomatico** [comment]
Fixed on version 1.7.2. Thanks @blackicedbear!

**Comment by AsHfIEXE** [comment]
I'm having same problem on 1.7.5

**Comment by glomatico** [comment]
Fixed on 1.8

**Comment by C45b0n** [comment]
> Fixed on 1.8

now following Error: 
C:\Users\*\Downloads>spotify-web-downloader -p https://open.spotify.com/playlist/*
[CRITICAL 07:57:57] .wvd file not found at device.wvd

**Comment by AsHfIEXE** [comment]
yes Im having widevine issue again on v1.8

**Comment by glomatico** [comment]
Reopening this issue since a lot of people are facing it once again.

**Comment by youngoris** [comment]
> I used this guide here: https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair-from-AVD

How to convert a CDM key pair to a .wvd file?

**Comment by pdtan** [comment]
> > I used this guide here: https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair-from-AVD
> 
> How to convert a CDM key pair to a .wvd file?

it has also .wvd

**Comment by youngoris** [comment]
> > > I used this guide here: https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair-from-AVD
> > 
> > 
> > How to convert a CDM key pair to a .wvd file?
> 
> it also has .wvd

still 403 error, 
when I play music in spotify app installed on that avd, there's no issue.

**Comment by GladistonXD** [comment]
I believe that the keys generated by Android Studio are not working, it would be necessary to generate them using a physical device, or some other emulator.

**Comment by betmoar** [comment]
SpotifyDL is working but using that wvd in this project results in error

**Comment by GladistonXD** [comment]
> [SpotifyDL](https://github.com/cycyrild/SpotifyDL) is working but using that wvd in this project results in error

SpotifyDL does not use any kind of file decryption key, it downloads the available songs from YouTube

**Comment by betmoar** [comment]
> > [SpotifyDL](https://github.com/cycyrild/SpotifyDL) is working but using that wvd in this project results in error
> 
> SpotifyDL does not use any kind of file decryption key, it downloads the available songs from YouTube

nope it used same decryption as this project

**Comment by GladistonXD** [comment]
> nope it used same decryption as this project

Aye thought it was another project with the same name that just did webscraping and downloaded from YouTube

**Comment by xMidNightFTW** [comment]
**Same issue here using 1.8.1**


```python
 [ERROR    14:28:02] (Track 1/1 from URL 1/1) Failed to download "same3 kelab btnb7"
 Traceback (most recent call last):
   File "Python\Python311\Lib\site-packages\spotify_web_downloader\utils.py", line 8, in check_response
     response.raise_for_status()
   File "Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "spotify_web_downloader\cli.py", line 518, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "spotify_web_downloader\downloader_song.py", line 35, in get_decryption_key
     license = self.downloader.spotify_api.get_widevine_license_music(challenge)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "spotify_web_downloader\spotify_api.py", line 127, in get_widevine_license_music
     check_response(response)
   File "spotify_web_downloader\utils.py", line 10, in check_response
     _raise_response_exception(response)
   File "spotify_web_downloader\utils.py", line 14, in _raise_response_exception
    raise Exception(
 Exception: Request failed with status code 403:
 [INFO     14:28:02] Done (1 error(s))
```

**Comment by GladistonXD** [comment]
I was only able to successfully obtain a functional widevine key with a mobile device with android 14, without success with emulators and devices with old android, apparently spotify banned old and emulator fingerprints

**Comment by youngoris** [comment]
success with a Android 12 mobile device too, and rooted by Magisk.

GladistonXD ***@***.***>于2024年9月21日 周六下午12:26写道：

**Comment by pdtan** [comment]
I'm still fine with AVD
